export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_ALL_EVENTS = "GET_ALL_EVENTS";
export const CREATE_EVENTS = "CREATE_EVENTS";

export const UPDATE_EVENTS = "UPDATE_EVENTS";

export const DELETE_EVENTS = "DELETE_EVENTS";

export const LIKE_EVENTS = "LIKE_EVENTS";

